feat: added job Priorities
MapColonies/discrete-ingestion-db pull request #21
Opened 2021-04-28 07:49 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         |  ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

- added priorities support
- fixed lint warnings

Further  information:

2021-04-28 08:17 UTC, asafMasa requested changes

2021-04-28 08:17 UTC, asafMasa commented on src/jobs/models/taskManager.ts
> +    return res;
add log of what was retrieved?

2021-04-28 08:17 UTC, asafMasa commented on src/jobs/routes/taskRouter.ts
> +  router.post('/:jobType/:taskType/startPending', tasksController.retrieveAndStart);
add integration test

2021-04-29 07:20 UTC, cl-shaharshavit-rnd commented on src/jobs/models/taskManager.ts
> +    return res;
added

2021-04-29 07:21 UTC, cl-shaharshavit-rnd commented on src/jobs/routes/taskRouter.ts
> +  router.post('/:jobType/:taskType/startPending', tasksController.retrieveAndStart);
added

2021-04-29 08:27 UTC, asafMasa approved these changes

2021-04-29 08:27 UTC, merged