feat: add Job constarint
MapColonies/discrete-ingestion-db pull request #49
Opened 2022-01-03 19:23 UTC by asafMasa

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2022-01-04 09:30 UTC, cl-shaharshavit-rnd requested changes

2022-01-04 09:30 UTC, cl-shaharshavit-rnd commented on openapi3.yaml
> +        extraConstraintData:
additionalIdentifiers

is better name

2022-01-04 09:30 UTC, cl-shaharshavit-rnd commented on src/DAL/entity/job.ts
> +  public extraConstraintData: string;
additionalIdentifiers

is better name

2022-01-04 09:30 UTC, cl-shaharshavit-rnd commented on src/DAL/migration/FullSchema.sql
> +  "extraConstraintData" text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
why not null?

2022-01-04 09:30 UTC, cl-shaharshavit-rnd commented on src/DAL/migration/v3.1.3.sql
> +  ADD COLUMN "extraConstraintData" text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
why not null?

2022-01-04 09:30 UTC, cl-shaharshavit-rnd commented on src/common/dataModels/jobs.ts
> +  extraConstraintData?: string;
additionalIdentifiers

is better name

2022-01-04 09:30 UTC, cl-shaharshavit-rnd commented on tests/unit/DAL/jobModelConverter.spec.ts
> +        extraConstraintData: '',
additionalIdentifiers

is better name

2022-01-04 12:45 UTC, cl-shaharshavit-rnd requested changes

2022-01-04 12:45 UTC, cl-shaharshavit-rnd commented on src/DAL/entity/job.ts
> +  public additionalIdentifiers: string;
the typescript model is still not nullable.....

2022-01-04 13:38 UTC, cl-shaharshavit-rnd approved these changes

2022-01-05 10:27 UTC, AnguIar approved these changes

2022-01-05 10:35 UTC, merged