feat: add route for getting partial task by id
MapColonies/discrete-ingestion-db pull request #9
Opened 2021-02-08 15:28 UTC by shimoncohen

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

Related issues: #6 
Closes #6

2021-02-08 15:39 UTC, cl-shaharshavit-rnd requested changes
Where are the tests???

2021-02-08 15:39 UTC, cl-shaharshavit-rnd commented on src/partialTask/models/partialTaskManager.ts
> +      return Promise.reject();
add TODO for custom errors

2021-02-08 15:39 UTC, cl-shaharshavit-rnd commented on src/partialTask/models/partialTaskManager.ts
> +      return Promise.reject();
add TODO for custom errors

2021-02-08 15:42 UTC, shimoncohen commented
> Where are the tests???

Nowhere

2021-02-09 06:35 UTC, cl-shaharshavit-rnd approved these changes

2021-02-14 08:57 UTC, asafMasa commented on tests/integration/discreteTask/discreteTask.spec.ts
> +  discreteTaskCreateError,
mind lint error

2021-02-14 08:57 UTC, asafMasa commented on tests/integration/discreteTask/discreteTask.spec.ts
> +    //   // All requests with status code of 400
why is this commented?

2021-02-14 08:57 UTC, asafMasa commented on tests/integration/discreteTask/discreteTask.spec.ts
> +    //   it('get should return status code 500 on db error', async function () {
why is this commented?

2021-02-14 08:57 UTC, asafMasa commented on tests/integration/discreteTask/discreteTask.spec.ts
> +    //   it('update should return status code 500 on db error', async function () {
why is this commented?

2021-02-14 08:57 UTC, asafMasa commented on tests/integration/partialTask/helpers/data.ts
> +// const tasks = [
remove comments

2021-02-14 08:57 UTC, asafMasa commented on tests/integration/partialTask/helpers/data.ts
> +// export const discreteTaskGetAll = {
remove comments

2021-02-14 08:57 UTC, asafMasa commented on tests/mocks/DiscreteManagerMock.ts
> +let discreteTaskManager: DiscreteTaskManager;
mind the lint comments

2021-02-14 09:27 UTC, cl-shaharshavit-rnd requested changes

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/integration/discreteTask/discreteTask.spec.ts
> +  discreteTaskCreateError,
remove if not used

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/integration/partialTask/helpers/data.ts
> +// const tasks = [
remove commented data if it isnt being used

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/mocks/DiscreteManagerMock.ts
> +let discreteTaskManager: DiscreteTaskManager;
it doesnt seams to be used or exported

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/mocks/DiscreteManagerMock.ts
> +const connectionManagerMock = ({
it doesnt seams to be used or exported

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/discreteTask/discreteTask.spec.ts
> +        expect(await discreteTaskManager.getDiscreteTask(discreteTaskGet.params)).toThrowError();
add "Error" type to the toThrow and TODO to replace with custom type

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/discreteTask/discreteTask.spec.ts
> +        ).toThrowError();
add "Error" type to the toThrow and TODO to replace with custom type

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/discreteTask/discreteTask.spec.ts
> +        expect(await discreteTaskManager.deleteDiscreteTask(discreteTaskDeleteError.params)).toThrowError();
add "Error" type to the toThrow and TODO to replace with custom type

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/helpers/data.ts
> +import { IPartialTaskCreate } from '../../../../src/common/interfaces';
remove if not used

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        expect(await partialTaskManager.getPartialTask(partialTaskGetError.params)).toThrowError();
add "Error" type to the toThrow and TODO to replace with custom type

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        expect(await partialTaskManager.getPartialTasksByDiscrete(partialTaskGetByDiscrete.params, SearchOrder.DESC)).toThrowError();
add "Error" type to the toThrow and TODO to replace with custom type

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        ).toThrowError();
add "Error" type to the toThrow and TODO to replace with custom type

2021-02-14 09:27 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        expect(await partialTaskManager.deleteResource(partialTaskDeleteError.params)).toThrowError();
add "Error" type to the toThrow and TODO to replace with custom type

2021-02-14 12:11 UTC, cl-shaharshavit-rnd requested changes

2021-02-14 12:11 UTC, cl-shaharshavit-rnd commented on tests/unit/discreteTask/discreteTask.spec.ts
> +        expect(await discreteTaskManager.getDiscreteTask(discreteTaskGet.params)).toThrowError();
should be 
toThrowError(Error)

2021-02-14 12:11 UTC, cl-shaharshavit-rnd commented on tests/unit/discreteTask/discreteTask.spec.ts
> +        ).toThrowError();
should be
toThrowError(Error)

2021-02-14 12:11 UTC, cl-shaharshavit-rnd commented on tests/unit/discreteTask/discreteTask.spec.ts
> +        expect(await discreteTaskManager.deleteDiscreteTask(discreteTaskDeleteError.params)).toThrowError();
should be
toThrowError(Error)

2021-02-14 12:11 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        expect(await partialTaskManager.getPartialTask(partialTaskGetError.params)).toThrowError();
should be
toThrowError(Error)

2021-02-14 12:11 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        expect(await partialTaskManager.getPartialTasksByDiscrete(partialTaskGetByDiscrete.params, SearchOrder.DESC)).toThrowError();
should be
toThrowError(Error)

2021-02-14 12:11 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        ).toThrowError();
should be
toThrowError(Error)

2021-02-14 12:11 UTC, cl-shaharshavit-rnd commented on tests/unit/partialTask/partialTask.spec.ts
> +        expect(await partialTaskManager.deleteResource(partialTaskDeleteError.params)).toThrowError();
should be
toThrowError(Error)

2021-02-14 12:39 UTC, cl-shaharshavit-rnd approved these changes

2021-02-14 13:27 UTC, merged